# constants.py

CLASS_WEAPONS = {'cleric':{True:['Club','Mace'],False:['Club','Mace','Sling','Staff','Warhammer']},'dwarf':{True:['Club','Dagger','Hand Axe','Javelin','Lance','Mace','Short Sword','Silver Dagger','Sword'],False:['Club','Dagger','Hand Axe','Javelin','Lance','Mace','Short Sword','Silver Dagger','Sword','Battle Axe','Crossbow','Short Bow','Sling','Spear','Staff','Warhammer']},'elf':{True:['Club','Dagger','Hand Axe','Javelin','Lance','Mace','Short Sword','Silver Dagger','Sword'],False:['Club','Dagger','Hand Axe','Javelin','Lance','Mace','Short Sword','Silver Dagger','Sword','Battle Axe','Crossbow','Long Bow','Polearm','Short Bow','Sling','Spear','Staff','Two Handed Sword','Warhammer']},'fighter':{True:['Club','Dagger','Hand Axe','Javelin','Lance','Mace','Short Sword','Silver Dagger','Sword'],False:['Club','Dagger','Hand Axe','Javelin','Lance','Mace','Short Sword','Silver Dagger','Sword','Battle Axe','Crossbow','Long Bow','Polearm','Short Bow','Sling','Spear','Staff','Two Handed Sword','Warhammer']},'halfling':{True:['Club','Dagger','Hand Axe','Mace','Short Sword','Silver Dagger','Sword'],False:['Club','Dagger','Hand Axe','Mace','Short Sword','Silver Dagger','Sword','Crossbow','Short Bow','Sling','Spear','Staff']},'magic user':{True:['Dagger','Silver Dagger'],False:['Dagger','Silver Dagger']},'thief':{True:['Club','Dagger','Hand Axe','Javelin','Lance','Mace','Short Sword','Silver Dagger','Sword'],False:['Club','Dagger','Hand Axe','Javelin','Lance','Mace','Short Sword','Silver Dagger','Sword','Battle Axe','Crossbow','Long Bow','Polearm','Short Bow','Sling','Spear','Staff','Two Handed Sword','Warhammer']}}
WEAPON_DAMAGE = {'Club':'1d4','Dagger':'1d4','Hand Axe':'1d6','Javelin':'1d4','Lance':'1d6','Mace':'1d6','Short Sword':'1d6','Silver Dagger':'1d4','Sword':'1d8','Battle Axe':'1d8','Crossbow':'1d6','Long Bow':'1d6','Polearm':'1d10','Short Bow':'1d6','Sling':'1d4','Spear':'1d6','Staff':'1d4','Two Handed Sword':'1d10','Warhammer':'1d6'}
CLASS_OPTIONS = ['cleric', 'dwarf', 'elf', 'fighter', 'halfling', 'magic user', 'thief']
CLASS_DISPLAY = { 'cleric' : 'Cleric', 'dwarf' : 'Dwarf', 'elf' : 'Elf', 'fighter' : 'Fighter', 'halfling' : 'Halfling', 'magic user' : 'Magic User', 'thief' : 'Thief'}
CLASS_REQS = {'dwarf': {'CON': 9}, 'elf': {'INT': 9}, 'halfling': {'CON': 9, 'DEX': 9}}
STANDARD_BONUS = { 3 : -3, 4 : -2, 5 : -2, 6 : -1, 7 : -1, 8 : -1, 9 : 0, 10 : 0, 11 : 0, 12 : 0, 13 : 1, 14 : 1, 15 : 1, 16 : 2, 17 : 2, 18 : 3 }
ALTERNATIVE_BONUS = { 3 : -2, 4 : -1, 5 : -1, 6 : -1, 7 : -1, 8 : -1, 9 : 0, 10 : 0, 11 : 0, 12 : 0, 13 : 1, 14 : 1, 15 : 1, 16 : 1, 17 : 1, 18 : 2 }
STR_OPEN_DOORS = { 3 : 1, 4 : 1, 5 : 1, 6 : 1, 7 : 1, 8 : 1, 9 : 2, 10 : 2, 11 : 2, 12 : 2, 13 : 3, 14 : 3, 15 : 3, 16 : 4, 17 : 4, 18 : 5}
INT_LANGUAGES = { 3 : 'broken speech', 4 : 'Native', 5 : 'Native', 6 : 'Native', 7 : 'Native', 8 : 'Native', 9 : 'Native', 10 : 'Native', 11 : 'Native', 12 : 'Native', 13 : 'Native + 1 Additional', 14 : 'Native + 1 Additional', 15 : 'Native + 1 Additional', 16 : 'Native + 2 Additional', 17 : 'Native + 2 Additional', 18 : 'Native + 3 Additional' }
INT_LITERACY = { 3 : False, 4 : False, 5 : False, 6 : True, 7 : True, 8 : True, 9 : True, 10 : True, 11 : True, 12 : True, 13 : True, 14 : True, 15 : True, 16 : True, 17 : True, 18 : True }
SAVING_THROWS = { 'cleric' : [ 11, 12, 14, 16, 15 ], 'dwarf' : [ 8, 9, 10, 13, 12 ], 'elf' : [ 12, 13, 13, 15, 15 ], 'fighter' : [ 12, 13, 14, 15, 16 ], 'halfling' : [ 8, 9, 10, 13, 12 ], 'magic user' : [ 13, 14, 13, 16, 15 ], 'thief' : [ 13, 14, 13, 16, 15 ], }
CLASS_HD = { 'cleric' : '1d6', 'dwarf' : '1d8', 'elf' : '1d6', 'fighter' : '1d8', 'halfling' : '1d6', 'magic user' : '1d4', 'thief' : '1d4', }
ALIGNMENT_OPTIONS = ['Lawful', 'Neutral']
CLASS_ARMOR_OPTIONS = { 'cleric' : [ 'Unarmoured', 'Leather', 'Chainmail' ], 'dwarf' : [ 'Unarmoured', 'Leather', 'Chainmail' ], 'elf' : [ 'Unarmoured', 'Leather', 'Chainmail' ], 'fighter' : [ 'Unarmoured', 'Leather', 'Chainmail' ], 'halfling' : [ 'Unarmoured', 'Leather', 'Chainmail' ], 'magic user' : [ 'Unarmoured' ], 'thief' : [ 'Unarmoured', 'Leather' ] }
CLASS_SHIELD = { 'cleric' : True, 'dwarf' : True, 'elf' : True, 'fighter' : True, 'halfling' : True, 'magic user' : False, 'thief' : False }
ARMOR_CLASS = { 'Unarmoured': 9, 'Leather' : 7, 'Chainmail' : 5 }
ARMOR_BASE_MOVE = { 'Unarmoured': 120, 'Leather' : 90, 'Chainmail' : 60 }
CLASS_LISTEN = { 'cleric' : 1, 'dwarf' : 2, 'elf' : 2, 'fighter' : 1, 'halfling' : 2, 'magic user' : 1, 'thief' : 1 }
CLASS_SECRET_DOOR = { 'cleric' : 1, 'dwarf' : 1, 'elf' : 2, 'fighter' : 1, 'halfling' : 1, 'magic user' : 1, 'thief' : 1 }
CLASS_ROOM_TRAP = { 'cleric' : 1, 'dwarf' : 2, 'elf' : 1, 'fighter' : 1, 'halfling' : 1, 'magic user' : 1, 'thief' : 1 }
CLASS_XP_TO_LEVEL = { 'cleric' : 1500, 'dwarf' : 2200, 'elf' : 4000, 'fighter' : 2000, 'halfling' : 2000, 'magic user' : 2500, 'thief' : 1200 }
