# CONstants.py

CLASS_WEAPONS = {'cleric':{True:['club','mace'],False:['club','mace','sling','staff','warhammer']},'dwarf':{True:['club','dagger','hand axe','javelin','lance','mace','short sword','silver dagger','sword'],False:['club','dagger','hand axe','javelin','lance','mace','short sword','silver dagger','sword','battle axe','crossbow','short bow','sling','spear','staff','warhammer']},'elf':{True:['club','dagger','hand axe','javelin','lance','mace','short sword','silver dagger','sword'],False:['club','dagger','hand axe','javelin','lance','mace','short sword','silver dagger','sword','battle axe','crossbow','long bow','polearm','short bow','sling','spear','staff','two handed sword','warhammer']},'fighter':{True:['club','dagger','hand axe','javelin','lance','mace','short sword','silver dagger','sword'],False:['club','dagger','hand axe','javelin','lance','mace','short sword','silver dagger','sword','battle axe','crossbow','long bow','polearm','short bow','sling','spear','staff','two handed sword','warhammer']},'halfling':{True:['club','dagger','hand axe','mace','short sword','silver dagger','sword'],False:['club','dagger','hand axe','mace','short sword','silver dagger','sword','crossbow','short bow','sling','spear','staff']},'magic user':{True:['dagger','silver dagger'],False:['dagger','silver dagger']},'thief':{True:['club','dagger','hand axe','javelin','lance','mace','short sword','silver dagger','sword'],False:['club','dagger','hand axe','javelin','lance','mace','short sword','silver dagger','sword','battle axe','crossbow','long bow','polearm','short bow','sling','spear','staff','two handed sword','warhammer']}}
WEAPON_DAMAGE = {'club':'1d4','dagger':'1d4','hand axe':'1d6','javelin':'1d4','lance':'1d6','mace':'1d6','short sword':'1d6','silver dagger':'1d4','sword':'1d8','battle axe':'1d8','crossbow':'1d6','long bow':'1d6','polearm':'1d10','short bow':'1d6','sling':'1d4','spear':'1d6','staff':'1d4','two handed sword':'1d10','warhammer':'1d6'}
WEAPON_MELEE = {'club':True,'dagger':True,'hand axe':True,'javelin':True,'lance':True,'mace':True,'short sword':True,'silver dagger':True,'sword':True,'battle axe':True,'crossbow':False,'long bow':False,'polearm':'1d10','short bow':False,'sling':False,'spear':True,'staff':True,'two handed sword':'1d10','warhammer':True}
WEAPON_COST = {'club':3,'dagger':3,'hand axe':4,'javelin':1,'lance':5,'mace':5,'short sword':7,'silver dagger':30,'sword':10,'battle axe':7,'crossbow':30,'long bow':4,'polearm':7,'short bow':25,'sling':2,'spear':3,'staff':2,'two handed sword':15,'warhammer':5}
CLASS_OPTIONS = ['cleric', 'dwarf', 'elf', 'fighter', 'halfling', 'magic user', 'thief']
CLASS_DISPLAY = { 'cleric' : 'cleric', 'dwarf' : 'dwarf', 'elf' : 'elf', 'fighter' : 'fighter', 'halfling' : 'halfling', 'magic user' : 'magic user', 'thief' : 'thief'}
CLASS_REQS = {'dwarf': {'CON': 9}, 'elf': {'INT': 9}, 'halfling': {'CON': 9, 'DEX': 9}}
STANDARD_BONUS = { 3 : -3, 4 : -2, 5 : -2, 6 : -1, 7 : -1, 8 : -1, 9 : 0, 10 : 0, 11 : 0, 12 : 0, 13 : 1, 14 : 1, 15 : 1, 16 : 2, 17 : 2, 18 : 3 }
ALTERNATIVE_BONUS = { 3 : -2, 4 : -1, 5 : -1, 6 : -1, 7 : -1, 8 : -1, 9 : 0, 10 : 0, 11 : 0, 12 : 0, 13 : 1, 14 : 1, 15 : 1, 16 : 1, 17 : 1, 18 : 2 }
STR_OPEN_DOORS = { 3 : 1, 4 : 1, 5 : 1, 6 : 1, 7 : 1, 8 : 1, 9 : 2, 10 : 2, 11 : 2, 12 : 2, 13 : 3, 14 : 3, 15 : 3, 16 : 4, 17 : 4, 18 : 5}
INT_LANGUAGES = { 3 : 'broken speech', 4 : 'native', 5 : 'native', 6 : 'native', 7 : 'native', 8 : 'native', 9 : 'native', 10 : 'native', 11 : 'native', 12 : 'native', 13 : 'native + 1 additional', 14 : 'native + 1 additional', 15 : 'native + 1 additional', 16 : 'native + 2 additional', 17 : 'native + 2 additional', 18 : 'native + 3 additional' }
INT_LITERACY = { 3 : False, 4 : False, 5 : False, 6 : True, 7 : True, 8 : True, 9 : True, 10 : True, 11 : True, 12 : True, 13 : True, 14 : True, 15 : True, 16 : True, 17 : True, 18 : True }
SAVING_THROWS = { 'cleric' : [ 11, 12, 14, 16, 15 ], 'dwarf' : [ 8, 9, 10, 13, 12 ], 'elf' : [ 12, 13, 13, 15, 15 ], 'fighter' : [ 12, 13, 14, 15, 16 ], 'halfling' : [ 8, 9, 10, 13, 12 ], 'magic user' : [ 13, 14, 13, 16, 15 ], 'thief' : [ 13, 14, 13, 16, 15 ], }
CLASS_HD = { 'cleric' : '1d6', 'dwarf' : '1d8', 'elf' : '1d6', 'fighter' : '1d8', 'halfling' : '1d6', 'magic user' : '1d4', 'thief' : '1d4', }
ALIGNMENT_OPTIONS = ['lawful', 'neutral']
CLASS_ARMOR_OPTIONS = { 'cleric' : [ 'unarmoured', 'leather', 'chainmail' ], 'dwarf' : [ 'unarmoured', 'leather', 'chainmail' ], 'elf' : [ 'unarmoured', 'leather', 'chainmail' ], 'fighter' : [ 'unarmoured', 'leather', 'chainmail' ], 'halfling' : [ 'unarmoured', 'leather', 'chainmail' ], 'magic user' : [ 'unarmoured' ], 'thief' : [ 'unarmoured', 'leather' ] }
CLASS_SHIELD = { 'cleric' : True, 'dwarf' : True, 'elf' : True, 'fighter' : True, 'halfling' : True, 'magic user' : False, 'thief' : False }
ARMOR_CLASS = { 'unarmoured': 9, 'leather' : 7, 'chainmail' : 5 }
ARMOR_BASE_MOVE = { 'unarmoured': 120, 'leather' : 90, 'chainmail' : 60 }
CLASS_LISTEN = { 'cleric' : 1, 'dwarf' : 2, 'elf' : 2, 'fighter' : 1, 'halfling' : 2, 'magic user' : 1, 'thief' : 1 }
CLASS_SECRET_DOOR = { 'cleric' : 1, 'dwarf' : 1, 'elf' : 2, 'fighter' : 1, 'halfling' : 1, 'magic user' : 1, 'thief' : 1 }
CLASS_ROOM_TRAP = { 'cleric' : 1, 'dwarf' : 2, 'elf' : 1, 'fighter' : 1, 'halfling' : 1, 'magic user' : 1, 'thief' : 1 }
CLASS_XP_TO_LEVEL = { 'cleric' : 1500, 'dwarf' : 2200, 'elf' : 4000, 'fighter' : 2000, 'halfling' : 2000, 'magic user' : 2500, 'thief' : 1200 }
